apiVersion: v1
kind: Namespace
metadata:
  name: kube-college
---
apiVersion: v1
kind: Secret
metadata:
  name: "kube-college-flag"
  namespace: kube-college
type: Opaque
data:
  flag: "ZmxhZ3t5b3UtY2FuLWludGVyYWN0LXdpdGgta3ViZXJuZXRlc30K"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: student
  namespace: kube-college
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: student
  namespace: kube-college
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: student
subjects:
- kind: ServiceAccount
  name: student
  namespace: kube-college
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: student
  namespace: kube-college
rules:
- apiGroups:
    - "*"
  resources: ["*"]
  verbs: ["get", "list", "watch"]
